remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Avian Genomic
description: My goal is to share what I learn about birds using bioinformatics.
